# Generated by Django 5.2.15 on 2026-07-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_alter_fotografia_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('SEGURANÇA', 'Segurança'), ('LOGISTICA', 'Logistica'), ('GA', 'GA'), ('EQUIPE', 'Equipe'), ('AÇÕES PENDENTES', 'Ações Pendentes'), ('ANOMALIAS', 'Anomalias Ocorridas')], default='', max_length=100),
        ),
    ]
